spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-data-source-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    com:
      zaxxer: NONE

server:
  port: 0